#include "proto.h"

#include <assert.h>
#include <stddef.h>
#include <string.h>

static void seed_grammar(Rme7SlotDecl *slots) {
    for (int s = 0; s < RME7_SLOT_COUNT; s++) {
        slots[s] = (Rme7SlotDecl){
            .defined     = true,
            .custody     = RME7_CUSTODY_NONE,
            .office      = rme7_slot_office((Rme7Slot)s),
        };
    }
}

static void clear_slots(Rme7SlotDecl *slots) {
    for (int s = 0; s < RME7_SLOT_COUNT; s++)
        slots[s] = (Rme7SlotDecl){ .defined = false,
                                   .custody = RME7_CUSTODY_NONE,
                                   .office = nullptr };
}

void rme7_actor_init(Rme7Actor *actor, const char *name) {
    assert(actor != nullptr && name != nullptr);
    actor->name = name;
    seed_grammar(actor->slots);
}

void rme7_actor_generate_system_root(const Rme7Actor *actor,
                                     Rme7Proto *out, const char *name) {
    assert(actor != nullptr && out != nullptr && name != nullptr);
    *out = (Rme7Proto){
        .name     = name,
        .layer    = RME7_LAYER_SYSTEM,
        .parent   = nullptr,   /* nothing delegates into the actor */
        .origin   = { .kind = RME7_ORIGIN_ACTOR, .actor = actor },
        .declared_set = false,
    };
    memcpy(out->slots, actor->slots, sizeof out->slots);
    out->exhibits = rme7_profile_empty();
}

void rme7_proto_generate_user_root(const Rme7Proto *system_root,
                                   Rme7Proto *out, const char *name) {
    assert(system_root != nullptr && out != nullptr && name != nullptr);
    assert(system_root->layer == RME7_LAYER_SYSTEM &&
           "user roots are generated by the system root, and by nothing else");
    *out = (Rme7Proto){
        .name     = name,
        .layer    = RME7_LAYER_USER,
        .parent   = nullptr,   /* delegation never crosses the boundary */
        .origin   = { .kind = RME7_ORIGIN_PROTO, .proto = system_root },
        .declared_set = false,
    };
    memcpy(out->slots, system_root->slots, sizeof out->slots);
    out->exhibits = rme7_profile_empty();
}

bool rme7_proto_generate(const Rme7Proto *generator,
                         Rme7Proto *out, const char *name) {
    assert(generator != nullptr && out != nullptr && name != nullptr);
    if (generator->layer != RME7_LAYER_USER) return false;
    *out = (Rme7Proto){
        .name     = name,
        .layer    = RME7_LAYER_USER,
        .parent   = generator,  /* inside the layer, delegate rather than copy */
        .origin   = { .kind = RME7_ORIGIN_PROTO, .proto = generator },
        .declared_set = false,
    };
    clear_slots(out->slots);
    out->exhibits = rme7_profile_empty();
    return true;
}

void rme7_proto_define(Rme7Proto *proto, Rme7Slot slot,
                       Rme7Custody custody, const char *office) {
    assert(proto != nullptr && slot < RME7_SLOT_COUNT);
    proto->slots[slot] = (Rme7SlotDecl){
        .defined = true, .custody = custody,
        .office = office != nullptr ? office : rme7_slot_office(slot),
    };
}

bool rme7_proto_exhibit(Rme7Proto *proto, Rme7Slot slot) {
    assert(proto != nullptr && slot < RME7_SLOT_COUNT);
    if (rme7_proto_resolve(proto, slot, nullptr) == nullptr) return false;
    rme7_profile_set(&proto->exhibits, slot, true);
    return true;
}

void rme7_proto_unexhibit(Rme7Proto *proto, Rme7Slot slot) {
    assert(proto != nullptr && slot < RME7_SLOT_COUNT);
    rme7_profile_set(&proto->exhibits, slot, false);
}

bool rme7_proto_defines(const Rme7Proto *proto, Rme7Slot slot) {
    return rme7_proto_resolve(proto, slot, nullptr) != nullptr;
}

const Rme7SlotDecl *rme7_proto_resolve(const Rme7Proto *proto, Rme7Slot slot,
                                       const Rme7Proto **found_in) {
    assert(slot < RME7_SLOT_COUNT);
    for (const Rme7Proto *p = proto; p != nullptr; p = p->parent) {
        if (p->slots[slot].defined) {
            if (found_in != nullptr) *found_in = p;
            return &p->slots[slot];
        }
    }
    if (found_in != nullptr) *found_in = nullptr;
    return nullptr;
}

Rme7Profile rme7_proto_profile(const Rme7Proto *proto) {
    assert(proto != nullptr);
    return proto->exhibits;   /* local: exhibition is evidence, not lineage */
}

Rme7Cast rme7_proto_classify(const Rme7Proto *proto) {
    return rme7_profile_classify(rme7_proto_profile(proto));
}

const Rme7Payload *rme7_proto_payload(const Rme7Proto *proto) {
    assert(proto != nullptr);
    return &proto->payload;   /* local only, by design */
}

void rme7_proto_declare(Rme7Proto *proto, Rme7Rung rung) {
    assert(proto != nullptr);
    proto->declared = rung;
    proto->declared_set = true;
}

bool rme7_proto_delta_level(const Rme7Proto *proto, int *out) {
    assert(proto != nullptr);
    if (!proto->declared_set) return false;
    Rme7Cast cast = rme7_proto_classify(proto);
    if (cast.kind != RME7_CAST_RUNG) return false;
    if (out != nullptr) *out = rme7_delta_level(cast.rung, proto->declared);
    return true;
}

bool rme7_proto_delegates_to(const Rme7Proto *proto, const Rme7Proto *ancestor) {
    if (ancestor == nullptr) return false;
    for (const Rme7Proto *p = proto; p != nullptr; p = p->parent)
        if (p == ancestor) return p != proto;
    return false;
}

bool rme7_proto_descends_from(const Rme7Proto *proto, const Rme7Proto *origin) {
    if (origin == nullptr) return false;
    for (const Rme7Proto *p = proto; p != nullptr; ) {
        if (p->origin.kind != RME7_ORIGIN_PROTO || p->origin.proto == nullptr)
            return false;
        if (p->origin.proto == origin) return true;
        p = p->origin.proto;
    }
    return false;
}
