#ifndef MOOP_RME7_H
#define MOOP_RME7_H

#include <stdbool.h>
#include <stddef.h>
#include "proto.h"

/* The RME-7 slots: one proto per primitive, on the object ladder.
 *
 * RME-7 (prompts/asdg-rme7.md) has seven primitives. Here each is a
 * SLOT — an ordinary user-facing proto, generated by `port`, which the
 * user-facing root generates. A slot is filled by teaching it from the
 * surface language; nothing is hosted, nothing is decided here. The
 * slots are bodies on the substrate (reversible and homoiconic by
 * construction), hereditary, MAYBE-seeded, and named. That is all. */

typedef enum {
    MOOP_RME7_JSHARP,       /* J♯ */
    MOOP_RME7_GSHARP,       /* G♯ */
    MOOP_RME7_GTILDESHARP,  /* G̃♯ */
    MOOP_RME7_SIGMA,        /* Σ */
    MOOP_RME7_F,            /* F */
    MOOP_RME7_KAPPA,        /* κ */
    MOOP_RME7_GAMMA,        /* γ */
    MOOP_RME7_PRIMITIVES,
} MoopRme7Primitive;

/* Largest loop the slots are built with. */
#define MOOP_RME7_MAX_CELLS 16

typedef struct {
    MoopProto port;                          /* generated by the user root */
    MoopProto slots[MOOP_RME7_PRIMITIVES];   /* generated by `port` */

    /* tape storage, one body each: [0] is `port`, [1 + i] is primitive i */
    bool cells_a[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool marks_a[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool cells_b[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool marks_b[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
} MoopRme7;

/* The surface name of each slot (`jsharp`, `gsharp`, ...). */
const char *moop_rme7_name(MoopRme7Primitive p);

/* A user-facing root generates `port`, and `port` generates the slots.
 * Bodies get len_a / len_b cells (≤ MAX_CELLS; coprime and ≥ 2 — the
 * core asserts). Returns false, touching nothing, if `root` is not
 * user-facing: the slots live in the user layer. */
bool moop_rme7_generate(MoopProto *root, MoopRme7 *fw,
                        size_t len_a, size_t len_b);

#endif
