#ifndef MOOP_RME7_H
#define MOOP_RME7_H

#include <stdbool.h>
#include <stddef.h>
#include "proto.h"

/* The RME-7 framework's ports, as protos on the object ladder.
 *
 * RME-7 (prompts/asdg-rme7.md) writes one object as a track — state X
 * and generator θ — and relates tracks only through PORTS, Σ_ij =
 * adapter ∘ gate ∘ translation. moop already has that shape: `<->`
 * translates a value onto tape cells (src/encode.c), refuses what does
 * not fit (the gate), and deposits or exchanges with gates (the
 * adapter). So no new coupling mechanism is added here. What this
 * module adds is the framework's OBJECTS: the user-facing root
 * generates a `port` proto, and `port` generates one proto per RME-7
 * primitive, so the framework's handles are bodies on the substrate —
 * reversible and homoiconic by construction, hereditary like any
 * user-facing proto, and addressable from the surface language.
 *
 * Each port proto answers whether a cross-track port of its primitive
 * is admitted by the framework. Exactly one of four verdicts is true,
 * and the assignment is derived by the deletion test against the
 * multi-track realization card (docs/crossing.md, entry 3):
 *
 *   admitted  Σ (the port itself), κ (the gate factor of every port)
 *   refused   G♯ — a cross-track objective is CAPTURE, the framework's
 *             named failure condition
 *   absent    J♯ (shared circulation merges two tracks into one),
 *             F (dissolves: Σ_ij delivers into X_i and F_i picks it up),
 *             γ (derived, not an operator; nothing to carry)
 *   open      G̃♯ — block-diagonal by the card, yet the composite
 *             predicate permits cross-sector confinement; not ours to
 *             rule
 *
 * The verdict vocabulary is hosted once, on `port`; the primitives
 * answer through ordinary delegation with the receiver as self. A port
 * born from a primitive inherits its verdict; one born from `port`
 * directly has no primitive and is `open`. Handlers only read lineage:
 * they never touch a body. */

typedef enum {
    MOOP_RME7_JSHARP,       /* J♯  conservative circulation */
    MOOP_RME7_GSHARP,       /* G♯  dissipative; the only office that converges */
    MOOP_RME7_GTILDESHARP,  /* G̃♯  confinement without convergence */
    MOOP_RME7_SIGMA,        /* Σ   stochastic driving; the port */
    MOOP_RME7_F,            /* F   generator-level self-modification */
    MOOP_RME7_KAPPA,        /* κ   integrity gate on generator modification */
    MOOP_RME7_GAMMA,        /* γ = [G♯, G̃♯], derived */
    MOOP_RME7_PRIMITIVES,
} MoopRme7Primitive;

typedef enum {
    MOOP_PORT_ADMITTED,
    MOOP_PORT_REFUSED,
    MOOP_PORT_ABSENT,
    MOOP_PORT_OPEN,
    MOOP_PORT_VERDICTS,
} MoopPortVerdict;

/* Largest loop the framework's bodies are built with. */
#define MOOP_RME7_MAX_CELLS 16

typedef struct {
    MoopProto port;                          /* generated by the user root */
    MoopProto ports[MOOP_RME7_PRIMITIVES];   /* generated by `port` */

    /* tape storage, one body each: [0] is `port`, [1 + i] is primitive i */
    bool cells_a[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool marks_a[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool cells_b[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];
    bool marks_b[1 + MOOP_RME7_PRIMITIVES][MOOP_RME7_MAX_CELLS];

    MoopProtoMessage port_table[MOOP_PORT_VERDICTS];
} MoopRme7;

/* Surface names: the word each primitive is bound to (`jsharp`, ...). */
const char *moop_rme7_name(MoopRme7Primitive p);

/* The verdict the framework assigns to a cross-track port of `p`. */
MoopPortVerdict moop_rme7_verdict(MoopRme7Primitive p);

/* A user-facing root generates the framework: `port`, then one port
 * proto per primitive. Bodies get len_a / len_b cells (≤ MAX_CELLS,
 * coprime, ≥ 2 — the core asserts). Generation is by MAYBE draws from
 * the generator, so it costs the root nothing irreversible. Returns
 * false (touching nothing) if `root` is not user-facing: the framework
 * lives in the user layer. */
bool moop_rme7_generate(MoopProto *root, MoopRme7 *fw,
                        size_t len_a, size_t len_b);

/* The verdict a proto answers with: that of its nearest ancestor among
 * the framework's primitives, or open if it descends from `port`
 * alone. Returns false if `p` is not in the framework's lineage. */
bool moop_rme7_verdict_of(const MoopRme7 *fw, const MoopProto *p,
                          MoopPortVerdict *out);

#endif
